#ifndef SECURE_OTA_GUARDIAN_APP_CONFIG_H
#define SECURE_OTA_GUARDIAN_APP_CONFIG_H

#define GUARDIAN_FIRMWARE_VERSION_MAJOR 0U
#define GUARDIAN_FIRMWARE_VERSION_MINOR 1U
#define GUARDIAN_FIRMWARE_VERSION_PATCH 0U
#define GUARDIAN_LCD_ENABLED             1
#define GUARDIAN_RC522_ENABLED           1

#endif
