"""
Data models and state definitions for dual-port telemetry and failover engine.
"""

from enum import Enum
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
import time


class PortId(str, Enum):
    PORT_A = "PORT_A"  # Primary IP
    PORT_B = "PORT_B"  # Backup Path
    BOTH = "BOTH"
    MESH = "MESH"


class SystemState(str, Enum):
    STATE_NORMAL = "STATE_NORMAL"          # Healthy (Green) - Port A active
    STATE_WARNING = "STATE_WARNING"        # Warning (Yellow) - Degradation score > 0.60
    STATE_FAILOVER_B = "FAILOVER_PORT_B"    # Failover (Orange) - Degrade > 0.85 or Critical > 0.50
    STATE_MESH_ACTIVE = "MESH_ACTIVE"      # Mesh Mode (Red) - Both ports critical


class PortMetric(BaseModel):
    """Network telemetry metrics for a single network port."""
    latency_ms: float = Field(..., description="Round-trip latency in milliseconds")
    jitter_ms: float = Field(..., description="Packet delay variation (jitter) in milliseconds")
    packet_loss_pct: float = Field(..., description="Packet loss percentage (0.0 - 100.0%)")
    dns_time_ms: float = Field(..., description="DNS resolution lookup time in milliseconds")

    def to_vector(self) -> List[float]:
        """Convert port metrics into a 4-dimensional vector."""
        return [
            round(self.latency_ms, 3),
            round(self.jitter_ms, 3),
            round(self.packet_loss_pct, 3),
            round(self.dns_time_ms, 3),
        ]


class DualTelemetrySample(BaseModel):
    """Synchronized dual-port telemetry sample at a specific timestamp."""
    timestamp: float = Field(default_factory=time.time)
    port_a: PortMetric
    port_b: PortMetric

    def to_8d_vector(self) -> List[float]:
        """Return the 8-dimensional feature vector [A_lat, A_jit, A_loss, A_dns, B_lat, B_jit, B_loss, B_dns]."""
        return self.port_a.to_vector() + self.port_b.to_vector()


class HealthEvaluation(BaseModel):
    """Link health assessment generated by the state machine every 500ms."""
    timestamp: float = Field(default_factory=time.time)
    state: SystemState
    active_path: PortId
    port_a_degradation_score: float
    port_a_critical_score: float
    port_b_degradation_score: float
    port_b_critical_score: float
    window_samples_count: int
    feature_vector_8d_mean: List[float]
    message: str = ""
    mesh_activated: bool = False


class NetworkDegradationProfile(BaseModel):
    """Network fault injection profile."""
    port: PortId = PortId.PORT_A
    latency_spike_ms: float = 280.0
    packet_loss_spike_pct: float = 35.0
    jitter_spike_ms: float = 25.0
    dns_spike_ms: float = 120.0
    duration_sec: float = 10.0
    start_time: float = Field(default_factory=time.time)
    active: bool = True
